### ISSUE TITLE
Git clone connection timeout

### ISSUE THREAD

**Issue by caseyjp11** [UfoDriver/yakuake-sessions#3]
I've seen a few applications failing like this due to changes with github. I cannot build the package because of this:
Cloning into 'yakuake-sessions'...
fatal: unable to connect to github.com:
github.com[0: 140.82.113.4]: errno=Connection timed out

**Comment by UfoDriver** [comment]
@caseyjp11 I have nothing to do with it, probably you have network issue.

**Comment by caseyjp11** [comment]
Perhaps this is a pkg issue. Other -git installs are working just fine. Nothing I could see in the build would indicate anything is wrong, but, eh. Thanks for the fast response.

**Comment by UfoDriver** [comment]
Well, from the message it's clear that your system cannot connect to github. If it's only for that repo, I can think only of one explanation - github uses different IPs for different repos and you have connection problem with that exact IP.

**Comment by caseyjp11** [comment]
Turns out it was a pkgbuild issue. Nothing I could see, but the maintainer recognized the issue right away. All settled. tyvm for your responses! :-)
